"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";
import EndUserLayout from "@/components/layouts/EndUserLayout";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import AdminLayout from "@/components/layouts/AdminLayout";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hideLayoutRoute = pathname == "/admin";
  const isAdminRoute = pathname.startsWith("/admin") && pathname != "/admin";
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
          <ReactQueryProvider>
            <div>
              {/* {hideLayoutRoute?{children}:isAdminRoute ? (
                <AdminLayout>{children}</AdminLayout>
              ) : (
                <EndUserLayout>{children}</EndUserLayout>
              )} */}
              {hideLayoutRoute ? (
                <>{children}</>
              ) : isAdminRoute ? (
                <AdminLayout>{children}</AdminLayout>
              ) : (
                <EndUserLayout>{children}</EndUserLayout>
              )}
            </div>
          </ReactQueryProvider>
        </Provider>
      </body>
    </html>
  );
}
